#+title: mastermind-it
#+author: laooree
#+description: Mastermind game, but you're not the one playing.

* What is this doing?

This is a simple program that asks the user for a secret numeric sequence, and
then tries to guess it using [[https://en.wikipedia.org/wiki/Mastermind_(board_game)][Mastermind]] rules.

* How do I try it?

Simply run =main.py=. Type a numeric sequence (e.g. =179=), and wait for
the program to guess it. The length is arbitrary, but 4-digit or longer
sequences make the program slow.

* How does it work?

The solution process leverages information theory. The idea came from this
[[https://www.youtube.com/watch?v=v68zYyaEmEA&t=779s][3Blue1Brown's video]], and you should really have a look at it if you're
intrigued.

In few words, each time you make a guess and look at the hints you receive,
you're progressively narrowing the set of possible solutions. The information
that is provided by each guess depends on how many possible solutions you're
discarding: the more you cut the "solutions space", the more information you
get. Obviously, you can't know in advance how much information you'll get by
choosing a guess, as it depends on the solution. However, there are guesses that
tend to provide more information than others, and this trend depends on which
guesses are left on the set of possible guesses.

This program works by picking the guesses that maximize the expected information
value.
